export  const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export  const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export  const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export  const GET_EVENT_DETAILS_REQUEST = "GET_EVENT_DETAILS_REQUEST";
export  const GET_EVENT_DETAILS_SUCCESS = "GET_EVENT_DETAILS_SUCCESS";
export  const GET_EVENT_DETAILS_FAILURE = "GET_EVENT_DETAILS_FAILURE";