export  const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export  const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export  const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export  const GET_EVENT_DETAILS_REQUEST = "GET_EVENT_DETAILS_REQUEST";
export  const GET_EVENT_DETAILS_SUCCESS = "GET_EVENT_DETAILS_SUCCESS";
export  const GET_EVENT_DETAILS_FAILURE = "GET_EVENT_DETAILS_FAILURE";


export  const SEARCH_EVENT_VENUE_REQUEST = "SEARCH_EVENT_VENUE_REQUEST";
export  const SEARCH_EVENT_VENUE_SUCCESS = "SEARCH_EVENT_VENUE_SUCCESS";
export  const SEARCH_EVENT_VENUE_FAILURE = "SEARCH_EVENT_VENUE_FAILURE";